core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('core.urls', namespace='core')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('new-user/', views.register, name='new-user'),
    path('new-company/', views.newCompany, name='new-company'),
    path('users/', views.usersView, name='users'),
    # path('users/profile', views.profile, name='profile'),
    path('users/<int:profile_id>/', views.user_view, name='user'),
    path('users/invite/<int:profile_id>/', views.invite, name='invite'),
    path('users/invites/', views.invites, name='invites'),
    path('users/invites/accept/<int:invite_id>/', views.acceptInvite, name='accept-invite'),
    path('users/invites/delete/<int:invite_id>/', views.deleteInvite, name='delete-invite'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    assign = models.ManyToManyField(User)
    efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    dead_line = models.DateField()
    company = models.ForeignKey('register.Company', on_delete=models.CASCADE)
    complete_per = models.FloatField(max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)

    # add_date = models.DateField(auto_now_add=True)
    # upd_date = models.DateField(auto_now_add=False, auto_now=True)
    # add_date = models.DateField(auto_now_add=True)  # Stores creation date
    # upd_date = models.DateField(auto_now=True)  # Updates on every save


    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField(User)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

register/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project

# Create your models here.
class Company(models.Model):
    social_name = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    city = models.CharField(max_length=50)
    # found_date = models.DateField()

    class Meta:
        verbose_name_plural = 'Companies'
        ordering = ('name',)


    def __str__(self):
        return (self.name)

class UserProfile(models.Model):
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    project = models.ManyToManyField(Project, blank=True)

    def __str__(self):
        return (str(self.user))

    def invite(self, invite_profile):
        invite = Invite(inviter=self, invited=invite_profile)
        invites = invite_profile.received_invites.filter(inviter_id=self.id)
        if not len(invites) > 0:    # don't accept duplicated invites
            invite.save()

    def remove_friend(self, profile_id):
        friend = UserProfile.objects.filter(id=profile_id)[0]
        self.friends.remove(friend)



class Invite(models.Model):
    inviter = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='made_invites')
    invited = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='received_invites')

    def accept(self):
        self.invited.friends.add(self.inviter)
        self.inviter.friends.add(self.invited)
        self.delete()

    def __str__(self):
        return str(self.inviter)

register/forms.py
from django import forms
from register.models import Company as Comp
from register.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='E-mail', required=True)
    company = forms.ModelChoiceField(queryset=Comp.objects.all())

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'company',
            'password1',
            'password2',
        }

        labels = {
            'first_name': 'Name',
            'last_name': 'Last Name',
            'company': 'Company',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        # user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        company = self.cleaned_data['company']

        if commit:
            user.save()
            user_profile = UserProfile.objects.create(user=user, company=Comp.objects.get(name=company))
            user_profile.save()

        return user

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Retype Password'
        # self.fields['company'].widget.attrs['class'] = 'form-control'


class CompanyRegistrationForm(forms.Form):
    social_name = forms.CharField(max_length=80)
    name = forms.CharField(max_length=80)
    email = forms.EmailField()
    city = forms.CharField(max_length=50)
    # found_date = forms.DateField()

    class Meta:
        model = Comp


    def save(self, commit=True):
        company = Comp()
        company.social_name = self.cleaned_data['social_name']
        company.name = self.cleaned_data['name']
        company.email = self.cleaned_data['email']
        company.city = self.cleaned_data['city']
        # company.found_date = self.cleaned_data['found_date']

        if commit:
            company.save()


    def __init__(self, *args, **kwargs):
        super(CompanyRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['social_name'].widget.attrs['class'] = 'form-control'
        self.fields['social_name'].widget.attrs['placeholder'] = 'Social Name'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['city'].widget.attrs['class'] = 'form-control'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        

register/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect
from projects.models import Task
from .models import UserProfile
from .models import Invite
from .forms import RegistrationForm
from .forms import CompanyRegistrationForm
# from .forms import ProfilePictureForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            user = form.save()
            created = True
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            context = {'created' : created}
            return render(request, 'register/reg_form.html', context)
        else:
            return render(request, 'register/reg_form.html', context)
    else:
        form = RegistrationForm()
        context = {
            'form' : form,
        }
        return render(request, 'register/reg_form.html', context)


def usersView(request):
    users = UserProfile.objects.all()
    tasks = Task.objects.all()
    context = {
        'users': users,
        'tasks': tasks,
    }
    return render(request, 'register/users.html', context)

def user_view(request, profile_id):
    user = UserProfile.objects.get(id=profile_id)
    context = {
        'user_view' : user,
    }
    return render(request, 'register/user.html', context)


def newCompany(request):
    if request.method == 'POST':
        form = CompanyRegistrationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            form.save()
            created = True
            form = CompanyRegistrationForm()
            context = {
                'created' : created,
                'form' : form,
                       }
            return render(request, 'register/new_company.html', context)
        else:
            return render(request, 'register/new_company.html', context)
    else:
        form = CompanyRegistrationForm()
        context = {
            'form' : form,
        }
        return render(request, 'register/new_company.html', context)


def invites(request):
    return render(request, 'register/invites.html')


def invite(request, profile_id):
    profile_to_invite = UserProfile.objects.get(id=profile_id)
    logged_profile = get_active_profile(request)
    if not profile_to_invite in logged_profile.friends.all():
        logged_profile.invite(profile_to_invite)
    return redirect('core:index')


def deleteInvite(request, invite_id):
    logged_user = get_active_profile(request)
    logged_user.received_invites.get(id=invite_id).delete()
    return render(request, 'register/invites.html')


def acceptInvite(request, invite_id):
    invite = Invite.objects.get(id=invite_id)
    invite.accept()
    return redirect('register:invites')

def remove_friend(request, profile_id):
    user = get_active_profile(request)
    user.remove_friend(profile_id)
    return redirect('register:friends')


def get_active_profile(request):
    user_id = request.user.userprofile_set.values_list()[0][0]
    return UserProfile.objects.get(id=user_id)

register/templates/register/invites.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Invites</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
  <div id="ui-view" style="opacity: 1;"><div class="animated fadeIn">
    <div class="row">
    <div class="col-12">
        <div class="row">
            {% if logged_user.received_invites.count %}
            <!--<h3 class="lead">You have {{ logged_user.received_invites.count }} invite{{ logged_user.received_invites.count|pluralize }}.</h3>-->
            <table class="table table-responsive-sm table-hover table-outline mb-5 ">
                <thead class="thead-light">
                <tr>
                    <th class="text-center"><i class="fa fa-user"></i></th>
                    <th>User</th>
                    <th>Add / Delete</th>
                    <th>Company</th>
                    <th class="text-center">Friends*</th>
                    <th>Activity</th>
                </tr>
            </thead>
                    <tbody>
                        <!-- user -->
                        {% for invite in logged_user.received_invites.all %}
                        <tr>
                            <td class="text-center">
                                <div class="avatar">
                                <img src="{{ invite.inviter.img.url }}" class="img-avatar" alt="{{ user.email }}">
                                <span class="avatar-status badge-success"></span>
                                </div>
                            </td>
                            <td>
                                {% if invite.inviter.user.get_full_name %}
                                <div>{{ invite.inviter.user.get_full_name }}{% if invite.inviter.user.is_staff %} <span class="badge badge-pill badge-dark"> staff</span> {% endif %}</div>
                                {% else %}
                                <div>{{ invite.inviter.user.username }}{% if invite.inviter.user.is_staff %} <span class="badge badge-pill badge-dark"> staff</span> {% endif %}</div>
                                {% endif %}
                                <div class="small text-muted">
                                <span>Joined:</span> | {{ invite.inviter.user.date_joined }}
                                </div>
                            </td>
                            <td>
                                <a href="{% url 'register:accept-invite' invite_id=invite.id %}" class="badge badge-success text-white">Add friend</a>
                                <a href="{% url 'register:delete-invite' invite_id=invite.id %}" class="badge badge-danger text-white">Remove invite</a>
                            </td>
                            <td>
                                {{ invite.inviter.company }}
                            </td>
                            <td class="text-center">
                                <span class="badge badge-pill badge-dark">{{ invite.inviter.user.task_set.values.count }} ***</span>
                                <span class="badge badge-pill badge-dark"></span>
                            </td>
                            <td>
                                <div class="small text-muted">Last login</div>
                                <strong>{{ invite.inviter.user.last_login }}</strong>
                            </td>
                        </tr>
                        {% endfor %}
                        <!-- end user -->
                    </tbody>
                </table>
                {% else %}
                {% if user.is_authenticated %}
                    <h3 class="m-5">You have no invites :(</h3>
                {% else %}
                    <a href="{% url 'core:login' %}" class="nav-link display-4">Log in to see your invites</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</div>
{% endblock %}

register/templates/register/login.html
<!--{% extends 'core/base.html' %}-->
{% load static %}


{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Login</li>
{% endblock breadcrumb%}

{% block body %}
<body class="app flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group">
                    <div class="card p-4">
                        <div class="card-body">
                            <form method="post" action="{% url 'core:login' %}">
                                {% csrf_token %}
                                <h1>Login</h1>
                                <p class="text-muted">Sign In to your account</p>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                    </div>
                                    <input type="text"
                                       class="form-control"
                                       name="{{ login_form.username.name }}"
                                       placeholder="{{ login_form.username.label }}"
                                       id="{{ login_form.username.id_for_label }}"
                                       {% if login_form.username.value != None %}value="{{ login_form.username.value|stringformat:'s' }}"{% endif %}
                                       maxlength="{{ login_form.username.field.max_length }}"
                                       {% if login_form.username.field.required %}required{% endif %}>
                                </div>
                                <div class="input-group mb-4">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-asterisk"></i></span>
                                    </div>
                                    <input type="password"
                                       class="form-control"
                                       name="{{ login_form.password.name }}"
                                       placeholder="{{ login_form.password.label }}"
                                       id="{{ login_form.password.id_for_label }}"
                                       {% if login_form.password.value != None %}value="{{ login_form.password.value|stringformat:'s' }}"{% endif %}
                                       maxlength="{{ login_form.password.field.max_length }}"
                                       {% if login_form.password.field.required %}required{% endif %}>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-primary px-4">Login</button>
                                    </div>
                                   
                                    {% if login_form.errors %}
                                    <div class="alert alert-danger col-12 mt-3" role="alert">
                                        Wrong username or password
                                    </div>
                                    {% endif %}
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card text-white bg-primary py-5">
                        <div class="card-body text-center">
                            <div>
                                <h2>Sign up</h2>
                                <p class="mt-4">Register now, it's free.</p>
                                <a href="{% url 'register:new-user' %}" class="btn btn-primary active mt-3">Register Now!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

  <!-- Bootstrap and necessary plugins -->
    <script src="{% static 'core/vendors/js/jquery.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/popper.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/pace.min.js'%}"></script>
    <script src="{% static 'core/vendors/js/Chart.min.js'%}"></script>

  <!-- CoreUI main scripts -->

    <script src="{% static 'core/js/app.js'%}"></script>

  <!-- Plugins and scripts required by this views -->

  <!-- Custom scripts required by this view -->
    <script src="{% static 'core/js/main.js'%}"></script>

</body>

{% endblock %}

register/templates/register/profile.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Friends</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12">
                    <div class="social-box" style="height:110%">
                        <div class="card">
                            <div class="card-body">
                                <img src="{{ logged_user.img.url }}" class="img-avatar m-4" alt="{{ user }}" width="20%">
                                <br>
                                <form action="" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="custom-file col-md-4">
                                        {{ img_form.img }}
                                        <label class="custom-file-label btn-sm" for="validatedCustomFile">Update picture...</label>
                                        <div>
                                            <button class="btn btn-primary btn-sm my-2" type="submit">Upload</button>
                                        </div>
                                    </div>
                                </form>
                                <ul class="mt-4">
                                    <li>
                                        <a href="{% url 'register:user' profile_id=logged_user.id %}" class="text-dark">
                                            <strong>{{ logged_user.friends.all.count }}</strong>
                                        </a>
                                        <span>friends</span>
                                    </li>
                                    <li>
                                        <strong>{{ logged_user.user.project_set.all.count }}</strong>
                                        <span>projects</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mt-5">
                <div class="col-12">
                    <div class="social-box" style="">
                        <ul class="mt-3">
                            <li><span>Company: <a href="">{{ logged_user.company }}</a></span></li>
                            <li><span>Projects:
                                    {% for project in logged_user.user.project_set.all %}
                                        <a href="">{{ project.name }},</a>
                                    {% endfor %}
                                </span>
                            </li>
                        </ul>
                        <ul>
                            <li><span>Name: <a href="">{{ logged_user.user.get_full_name }}</a></span></li>
                            <li><span>e-mail: <span class="text-blue text-lowercase">{{ logged_user.user.email }}</span></span>
                            </li>
                        </ul>
                        <ul>
                            <li><span>Date joined: <span class="text-blue">{{ logged_user.user.date_joined }}</span></span></li>
                            <li><span>Last login: <span class="text-blue">{{ logged_user.user.last_login }}</span></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

register/templates/register/user.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Friends</li>
{% endblock breadcrumb%}

{% block content %}

<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12 mb-3">
                    <div class="social-box" style="height:110%">
                        <br>
                        <h6><i> {{ user_view }} </h6></i>
                        <ul>
                        <li>
                            <strong>{{ user_view.friends.all.count }}</strong>
                            <span>friends</span>
                        </li>
                        <li>
                            <strong>{{ user_view.project.all.count }}</strong>
                            <span>projects</span>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-5">
                        <div class="simple-box">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <ul class="mt-4 mx-5">
                                        <h5>Personal info:</h5>
                                        <li><span>Name:</span> {{ user_view.user.get_full_name }}</li>
                                        <li><span>Company:</span> {{ user_view.company }}</li>
                                        <li><span>E-mail:</span> {{ user_view.user.email}}</li>
                                        <li><span>Last login:</span> {{ user_view.user.last_login }}</li>
                                        {% comment %} <li><span>Date joined:</span> {{ user_view.user.date_joined }}</li> {% endcomment %}
                                    </ul>
                                </div>
                                <div class="col-12 col-md-6 text-left">
                                    <ul class="m-4">
                                        <h5>Tasks that {{ user_view.user.first_name }} is involved:</h5>
                                        {% for task in user_view.user.task_set.all %}
                                        <li>{{ task }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="card-body">
                                    <div class="tab-pane p-3 active show">
                                      <div class="message">
                                        <div class="py-3 pb-5 mr-3 float-left">
                                          <div class="avatar">
                                            <h3> {{ friend.user.get_full_name }} </h3>
                                            <span class="avatar-status badge-success"></span>
                                          </div>
                                        </div>
                                        <div>
                                          <small class="text-muted">{{ user_view.user.get_full_name }}</small>
                                            {% if user_view.user.last_login %}
                                          <small class="text-muted float-right mt-1">Last login: {{ user_view.user.last_login|date:"H:i" }} in {{ user_view.user.last_login|date:"d/m" }}</small>
                                            {% endif %}
                                        </div>
                                        <div class="text-truncate font-weight-bold">{{ user_view.company }}</div>
                                        {% if user_view.user.project_set %}
                                        <em class="text-muted">Projects that {{ user_view.user.first_name }} is working:</em>
                                        <small class="text-muted">
                                            {% for project in user_view.user.project_set.all %}
                                            {{ project }},
                                            {% endfor %}
                                        </small>
                                        {% else %}
                                        <em class="text-muted">{{ user_view.user.first_name }} is working in no projects until now.</em>
                                        {% endif %}
                                      </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}